spring.datasource.url=jdbc:mysql://HOST:PORT/railway
spring.datasource.username=root
spring.datasource.password=CvqEiVuvETJPIDYGQYsOMvafuSUHwBEk

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true