spring.datasource.url=jdbc:postgresql://dpg-d6of9esr85hc739diuo0-a/employees_xdhg


spring.datasource.username=employees_xdhg_user
spring.datasource.password=Mz1qYKLdnxkVbnx1k48Kh2FSjqP9tL0x


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update